// user
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const GET_CURERNT_USER = 'GET_CURERNT_USER';
export const FOREGT_PASSWORD = 'FOREGT_PASSWORD';
export const VERIFY_PASSWORD = 'VERIFY_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const GET_ALL_USER_ADDRESS = 'GET_ALL_USER_ADDRESS';
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS';
export const GET_ONE_USER_ADDRESS = 'GET_ONE_USER_ADDRESS';
export const EDIT_USER_ADDRESS = 'EDIT_USER_ADDRESS';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';

// hall
export const ADD_HALL = 'ADD_HALL';
export const GET_ALL_HALLS = 'GET_ALL_HALLS ';
export const GET_ADMIN_HALLS = 'GET_ADMIN_HALLS ';
export const SEARCH_HALLS = 'SEARCH_HALLS';
export const CHANGE_HALL_STATUS = 'CHANGE_HALL_STATUS';
export const GET_USER_HALLS = 'GET_USER_HALLS';
export const GET_HALL_RATE = 'GET_HALL_RATE';
export const ADD_HALL_RATE = 'ADD_HALL_RATE';
export const ALLOWED_USER_RATE = 'ALLOWED_USER_RATE';
export const GET_HALLS_CITIES = 'GET_HALLS_CITIES';

//book
export const RESERV_HALL_BY_HOUR = 'RESERV_HALL_BY_HOUR';
export const RESERV_HALL_BY_INTERVAL_Hours = 'RESERV_HALL_BY_INTERVAL_Hours';
export const RESERV_HALL_BY_INTERVAL_Days = 'RESERV_HALL_BY_INTERVAL_Days';
export const RESERV_HALL_BY_Days_Hours = 'RESERV_HALL_BY_INTERVAl_Days_Hours';

// message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

// checkout
export const CREATE_ORDER = 'CREATE_ORDER'; 
export const CHECK_ORDER_COMPLETE='CHECK_ORDER_COMPLETE'
export const Get_Hall_CODES='Get_Hall_CODES'
